MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"






Events with label "PR exists" and without label "List discussion needed"


Issues
------
* w3c/webrtc-pc (+0/-1/💬5)

  1 issues received 5 new comments:
  - #888 Section 6.2:  Issue 3 - buffered data at transport close (5 by alvestrand, feross, jesup, taylor-b)
    https://github.com/w3c/webrtc-pc/issues/888 [PR exists] 


  1 issues closed:
  - Section 6.2:  Issue 3 - buffered data at transport close https://github.com/w3c/webrtc-pc/issues/888 [PR exists] 








Repositories tracked by this digest:
-----------------------------------
* https://github.com/w3c/webrtc-pc




-- 
Sent with ♥
