MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"






Events with label "editorial"


Issues
------
* w3c/webrtc-pc (+1/-0/💬0)
  1 issues created:
  - Meta: auto-publish changes to the spec (by foolip)
    https://github.com/w3c/webrtc-pc/issues/942 [editorial] 


* w3c/webcrypto (+0/-0/💬1)
  1 issues received 1 new comments:
  - #86 Bug 29539 - Invalid algorithm OID for ECDH (1 by joakimb)
    https://github.com/w3c/webcrypto/issues/86 [editorial] 









Repositories tracked by this digest:
-----------------------------------
* https://github.com/w3c/webrtc-pc
* https://github.com/w3c/webcrypto




-- 
Sent with ♥
