Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: =?utf-8?q?W3C_Webmaster_via_GitHub_API?= <test@localhost>
To: dom@localhost
Subject: Weekly github digest (Issues with proposed edits)


Events filtered by label "PR exists"


Issues
------
* w3c/webrtc-pc (+0/-1/💬8)

  1 issues closed:
  - Section 6.2:  Issue 3 - buffered data at transport close 
https://github.com/w3c/webrtc-pc/issues/888


  2 issues received 8 new comments:
  - #888 Section 6.2:  Issue 3 - buffered data at transport close (5 
by jesup, feross, taylor-b, alvestrand)
    https://github.com/w3c/webrtc-pc/issues/888
  - #714 STUN/TURN OAuth token auth parameter passing (3 by juberti, 
misi)
    https://github.com/w3c/webrtc-pc/issues/714




Pull requests
-------------


Repositories tracked by this digest:
-----------------------------------
* https://github.com/w3c/webrtc-pc