MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"



Errors while compiling the digest:
 - Repo foo/bar/events yields 404 error


Issues
------
* w3c/webrtc-pc (+5/-2/💬12)
  5 issues created:
  - replaceTrack(null): Allowed? (by aboba)
    https://github.com/w3c/webrtc-pc/issues/947
  - sender.setParameters():  Changing simulcast parameters? (by aboba)
    https://github.com/w3c/webrtc-pc/issues/945
  - Effect of sender.replaceTrack(null) (by aboba)
    https://github.com/w3c/webrtc-pc/issues/943
  - Meta: auto-publish changes to the spec (by foolip)
    https://github.com/w3c/webrtc-pc/issues/942
  - STUN/TURN Auto Discovery handling (by misi)
    https://github.com/w3c/webrtc-pc/issues/941


  5 issues received 12 new comments:
  - #888 Section 6.2:  Issue 3 - buffered data at transport close (5 by jesup, feross, taylor-b, alvestrand)
    https://github.com/w3c/webrtc-pc/issues/888
  - #714 STUN/TURN OAuth token auth parameter passing (3 by juberti, misi)
    https://github.com/w3c/webrtc-pc/issues/714
  - #803 Rules for negotiation-needed flag need to be updated for transceivers. (2 by taylor-b, aboba)
    https://github.com/w3c/webrtc-pc/issues/803
  - #942 Meta: auto-publish changes to the spec (1 by henbos)
    https://github.com/w3c/webrtc-pc/issues/942
  - #927 What happens when setDirection() is called (1 by taylor-b)
    https://github.com/w3c/webrtc-pc/issues/927


  2 issues closed:
  - Rules for negotiation-needed flag need to be updated for transceivers. https://github.com/w3c/webrtc-pc/issues/803
  - Section 6.2:  Issue 3 - buffered data at transport close https://github.com/w3c/webrtc-pc/issues/888






Pull requests
-------------
* w3c/webrtc-pc (+8/-1/💬10)
  8 pull requests submitted:
  - Revert "Respec now uses yarn instead of npm" (by vivienlacourba)
    https://github.com/w3c/webrtc-pc/pull/948
  - Splitting transceiver direction into "direction" and "currentDirection". (by taylor-b)
    https://github.com/w3c/webrtc-pc/pull/946
  - Effect of setting sender.track to null (by aboba)
    https://github.com/w3c/webrtc-pc/pull/944
  - Use of "stopped" in insertDTMF and replaceTrack (by aboba)
    https://github.com/w3c/webrtc-pc/pull/940
  - Removed "stopped" from removeTrack (by aboba)
    https://github.com/w3c/webrtc-pc/pull/939
  - What happens when setDirection() is called (by aboba)
    https://github.com/w3c/webrtc-pc/pull/938
  - What happens when transceiver.stop() is called (by aboba)
    https://github.com/w3c/webrtc-pc/pull/937
  - Remove Issue 1: Current and Pending SDP (by aboba)
    https://github.com/w3c/webrtc-pc/pull/936


  7 pull requests received 10 new comments:
  - #944 Effect of setting sender.track to null (4 by pthatcherg, aboba)
    https://github.com/w3c/webrtc-pc/pull/944
  - #929 Have RTCSessionDescription's sdp member default to "" (1 by jan-ivar)
    https://github.com/w3c/webrtc-pc/pull/929
  - #939 Removed "stopped" from removeTrack (1 by aboba)
    https://github.com/w3c/webrtc-pc/pull/939
  - #940 Use of "stopped" in insertDTMF and replaceTrack (1 by aboba)
    https://github.com/w3c/webrtc-pc/pull/940
  - #920 Revise text dealing with with the ICE Agent/User Agent interactions. (1 by aboba)
    https://github.com/w3c/webrtc-pc/pull/920
  - #946 Splitting transceiver direction into "direction" and "currentDirection". (1 by aboba)
    https://github.com/w3c/webrtc-pc/pull/946
  - #919 Removing incorrect statement related to IP leaking issue. (1 by vivienlacourba)
    https://github.com/w3c/webrtc-pc/pull/919


  1 pull requests merged:
  - Respec now uses yarn instead of npm
    https://github.com/w3c/webrtc-pc/pull/935




Repositories tracked by this digest:
-----------------------------------
* https://github.com/w3c/webrtc-pc
* https://github.com/foo/bar
