MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: =?utf-8?q?Dominique_Haza=C3=ABl-Massieux_via_GitHub?= <test@localhost>
To: dom@localhost
Subject: [github-notify-ml] Move default values to config file (#1)
Message-ID: <issues.opened-45268120-1412787119-test@localhost>

dontcallmedom has just created a new issue for https://github.com/dontcallmedom/github-notify-ml:


== Move default values to config file ==
(which formats to use? .ini, .json, .yaml?)


Please view or discuss this issue at https://github.com/dontcallmedom/github-notify-ml/issues/1 using your GitHub account
