Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
From: test@localhost
To: dom@localhost
Subject: Re: [github-notify-ml] Move default values to config file
Message-ID: <issue_comment.created-58886897-test@localhost>
In-Reply-To: <issues.opened-45268120-test@localhost>

python has its own configuration format, let's use that one https://docs.python.org/2/library/configparser.html
-- 
GitHub Notif of comment by dontcallmedom
See https://github.com/dontcallmedom/github-notify-ml/issues/1#issuecomment-58886897