Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: =?utf-8?q?Dominique_Haza=C3=ABl-Massieux_via_GitHub_=3Ctest=40localhost?=
 =?utf-8?q?=3E?=
To: dom@localhost
Subject: [github-notify-ml] Move default values to config file
Message-ID: <issues.opened-45268120-1412787119-test@localhost>

dontcallmedom has just created a new issue for 
https://github.com/dontcallmedom/github-notify-ml:

== Move default values to config file ==
(which formats to use? .ini, .json, .yaml?)

See https://github.com/dontcallmedom/github-notify-ml/issues/1