Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
From: test@localhost
To: dom@localhost
Subject: [github-notify-ml] Move default values to config file
Message-ID: <issues.opened-45268120-test@localhost>

dontcallmedom has just created a new issue for https://github.com/dontcallmedom/github-notify-ml:

== Move default values to config file ==
(which formats to use? .ini, .json, .yaml?)

See https://github.com/dontcallmedom/github-notify-ml/issues/1