MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: =?utf-8?q?Dominique_Haza=C3=ABl-Massieux_via_GitHub?= <test@localhost>
To: dom@localhost
Subject: Re: [github-notify-ml] Move default values to config file (#1)
Message-ID: <issue_comment.created-58886897-1413204426-test@localhost>
In-Reply-To: <issues.opened-45268120-1412787119-test@localhost>

python has its own configuration format, let's use that one https://docs.python.org/2/library/configparser.html


-- 
GitHub Notification of comment by dontcallmedom
Please view or discuss this issue at https://github.com/dontcallmedom/github-notify-ml/issues/1#issuecomment-58886897 using your GitHub account
