MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: Anssi Kostiainen via GitHub <test@localhost>
To: dom@localhost
Subject: [presentation-api] Pull Request: Use the custom W3C Document License defined
 in the Charter
Message-ID: <pull_request.opened-29160635-1423729955-test@localhost>

anssiko has just submitted a new pull request for https://github.com/w3c/presentation-api:


== Use the custom W3C Document License defined in the Charter ==
The group's Charter defines a custom Document License [1] the documents produced by this group should use. To that end, I updated the Editor's Draft as well as the FPWD snapshot in staging accordingly.


@tidoust Pubrules checker naturally does not understand this custom Document License, so this needs to be checked manually.


[1] http://www.w3.org/2014/secondscreen/charter.html#doclicense


See https://github.com/w3c/presentation-api/pull/54
