MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: Stefan Hakansson via GitHub <test@localhost>
To: dom@localhost
Subject: Re: [mediacapture-main] Update text for how constraint dictionaries get
 extended 
Message-ID: <issue_comment.created-83934826-1426833268-test@localhost>
In-Reply-To: <pull_request.opened-31564006-1426797727-test@localhost>

I made a couple of minor comments, but overall this LGTM.


-- 
GitHub Notif of comment by stefhak
See https://github.com/w3c/mediacapture-main/pull/150#issuecomment-83934826
Special template!