MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: Tobie Langel via GitHub <test@localhost>
To: dom@localhost
Subject: [web-platform-tests] Pull Request: Adding a basic no-media call that uses
 promises.
Message-ID: <pull_request.labeled-35304013-None-test@localhost>

tobie has just labeled a pull request from alvestrand for https://github.com/w3c/web-platform-tests as "wg-webrtc":


== Adding a basic no-media call that uses promises. ==
This tests the basic promise machinery in PeerConnection.


Tested and works in Firefox; asking @jan-ivar to take a look because he's probably most passionate about how Promises usage should be styled.




See https://github.com/w3c/web-platform-tests/pull/1824
