MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: Harald Alvestrand via GitHub <test@localhost>
To: dom@localhost
Subject: [webrtc-pc] Merged Pull Request: Use unsigned long ssrc in stats
Message-ID: <pull_request.closed-53266014-1449763115-test@localhost>
In-Reply-To: <pull_request.opened-53266014-1449758254-test@localhost>

alvestrand has just merged dontcallmedom's pull request 433 for https://github.com/w3c/webrtc-pc:


== Use unsigned long ssrc in stats ==
close #390


See https://github.com/w3c/webrtc-pc/pull/433
