MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: =?utf-8?q?Dominique_Haza=C3=ABl-Massieux_via_GitHub?= <test@localhost>
To: dom@localhost
Subject: [github-notify-ml] new commits pushed by dontcallmedom
Message-ID: 
 <push-d3cb75fab91fd7dec6cd8fff69063405d31c505b-1412783833-test@localhost>

Per ml template!

The following commits were just pushed by dontcallmedom to https://github.com/dontcallmedom/github-notify-ml:


* basic template for pushes
  by Dominique Hazael-Massieux
https://github.com/dontcallmedom/github-notify-ml/commit/d3cb75fab91fd7dec6cd8fff69063405d31c505b


