Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
From: test@localhost
To: dom@localhost
Subject: [github-notify-ml]  new commits pushed by dontcallmedom
Message-ID: <push-d3cb75fab91fd7dec6cd8fff69063405d31c505b-test@localhost>


The following  commits were just pushed by dontcallmedom to https://github.com/dontcallmedom/github-notify-ml:
* basic template for pushes by Dominique Hazael-Massieux -- see https://github.com/dontcallmedom/github-notify-ml/commit/d3cb75fab91fd7dec6cd8fff69063405d31c505b
