Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: Dominique Hazael-Massieux via GitHub <test@localhost>
To: dom@localhost
Subject: [github-notify-ml]  new commits pushed by dontcallmedom
Message-ID: <push-d3cb75fab91fd7dec6cd8fff69063405d31c505b-test@localhost>


The following  commits were just pushed by dontcallmedom to https://github.=
com/dontcallmedom/github-notify-ml:
* basic template for pushes by Dominique Hazael-Massieux -- see https://git=
hub.com/dontcallmedom/github-notify-ml/commit/d3cb75fab91fd7dec6cd8fff69063=
405d31c505b
