MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: =?utf-8?q?Dominique_Haza=C3=ABl-Massieux_via_GitHub?= <test@localhost>
To: dom@localhost
Subject: w3c/test-repo-transfer transferred from dontcallmedom to w3c by dontcallmedom
Message-ID: <repository.transferred-267321549-None-test@localhost>

dontcallmedom has just transferred the repository test-repo-transfer from dontcallmedom to w3c
  https://github.com/w3c/test-repo-transfer