MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"; format="flowed"
From: W3C Webmaster via W3C API <test@localhost>
To: dom@localhost
Subject: "SHACL Use Cases and Requirements" published as a Working Draft

"SHACL Use Cases and Requirements" has just been published as a W3C Working Draft dated 2016-01-22 at http://www.w3.org/TR/2016/WD-shacl-ucr-20160122/.